package model.pojos;
// Generated 15/11/2012 09:54:45 AM by Hibernate Tools 3.2.1.GA



/**
 * Amistad generated by hbm2java
 */
public class Amistad  implements java.io.Serializable {


     private int idAmistad;
     private StatusAmistad statusAmistad;
     private int idUsuario1;
     private int idUsuario2;

    public Amistad() {
    }

    public Amistad(int idAmistad, StatusAmistad statusAmistad, int idUsuario1, int idUsuario2) {
       this.idAmistad = idAmistad;
       this.statusAmistad = statusAmistad;
       this.idUsuario1 = idUsuario1;
       this.idUsuario2 = idUsuario2;
    }
   
    public int getIdAmistad() {
        return this.idAmistad;
    }
    
    public void setIdAmistad(int idAmistad) {
        this.idAmistad = idAmistad;
    }
    public StatusAmistad getStatusAmistad() {
        return this.statusAmistad;
    }
    
    public void setStatusAmistad(StatusAmistad statusAmistad) {
        this.statusAmistad = statusAmistad;
    }
    public int getIdUsuario1() {
        return this.idUsuario1;
    }
    
    public void setIdUsuario1(int idUsuario1) {
        this.idUsuario1 = idUsuario1;
    }
    public int getIdUsuario2() {
        return this.idUsuario2;
    }
    
    public void setIdUsuario2(int idUsuario2) {
        this.idUsuario2 = idUsuario2;
    }




}


