package model.pojos;
// Generated 15/11/2012 05:32:04 PM by Hibernate Tools 3.2.1.GA



/**
 * Amistad generated by hbm2java
 */
public class Amistad  implements java.io.Serializable {


     private int idAmistad;
     private Usuario usuarioByIdUsuario1;
     private Usuario usuarioByIdUsuario2;
     private StatusAmistad statusAmistad;

    public Amistad() {
    }

    public Amistad(int idAmistad, Usuario usuarioByIdUsuario1, Usuario usuarioByIdUsuario2, StatusAmistad statusAmistad) {
       this.idAmistad = idAmistad;
       this.usuarioByIdUsuario1 = usuarioByIdUsuario1;
       this.usuarioByIdUsuario2 = usuarioByIdUsuario2;
       this.statusAmistad = statusAmistad;
    }
   
    public int getIdAmistad() {
        return this.idAmistad;
    }
    
    public void setIdAmistad(int idAmistad) {
        this.idAmistad = idAmistad;
    }
    public Usuario getUsuarioByIdUsuario1() {
        return this.usuarioByIdUsuario1;
    }
    
    public void setUsuarioByIdUsuario1(Usuario usuarioByIdUsuario1) {
        this.usuarioByIdUsuario1 = usuarioByIdUsuario1;
    }
    public Usuario getUsuarioByIdUsuario2() {
        return this.usuarioByIdUsuario2;
    }
    
    public void setUsuarioByIdUsuario2(Usuario usuarioByIdUsuario2) {
        this.usuarioByIdUsuario2 = usuarioByIdUsuario2;
    }
    public StatusAmistad getStatusAmistad() {
        return this.statusAmistad;
    }
    
    public void setStatusAmistad(StatusAmistad statusAmistad) {
        this.statusAmistad = statusAmistad;
    }




}


