package model.pojos;
// Generated 16/10/2012 06:13:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int idComentario;
     private Usuario usuarioByUsuarioReceptor;
     private Usuario usuarioByUsuarioEmisor;
     private Comentario comentario;
     private String comentario_1;
     private Date fecha;
     private Set comentarios = new HashSet(0);

    public Comentario() {
    }

	
    public Comentario(int idComentario, Usuario usuarioByUsuarioReceptor, Usuario usuarioByUsuarioEmisor, String comentario_1, Date fecha) {
        this.idComentario = idComentario;
        this.usuarioByUsuarioReceptor = usuarioByUsuarioReceptor;
        this.usuarioByUsuarioEmisor = usuarioByUsuarioEmisor;
        this.comentario_1 = comentario_1;
        this.fecha = fecha;
    }
    public Comentario(int idComentario, Usuario usuarioByUsuarioReceptor, Usuario usuarioByUsuarioEmisor, Comentario comentario, String comentario_1, Date fecha, Set comentarios) {
       this.idComentario = idComentario;
       this.usuarioByUsuarioReceptor = usuarioByUsuarioReceptor;
       this.usuarioByUsuarioEmisor = usuarioByUsuarioEmisor;
       this.comentario = comentario;
       this.comentario_1 = comentario_1;
       this.fecha = fecha;
       this.comentarios = comentarios;
    }
   
    public int getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(int idComentario) {
        this.idComentario = idComentario;
    }
    public Usuario getUsuarioByUsuarioReceptor() {
        return this.usuarioByUsuarioReceptor;
    }
    
    public void setUsuarioByUsuarioReceptor(Usuario usuarioByUsuarioReceptor) {
        this.usuarioByUsuarioReceptor = usuarioByUsuarioReceptor;
    }
    public Usuario getUsuarioByUsuarioEmisor() {
        return this.usuarioByUsuarioEmisor;
    }
    
    public void setUsuarioByUsuarioEmisor(Usuario usuarioByUsuarioEmisor) {
        this.usuarioByUsuarioEmisor = usuarioByUsuarioEmisor;
    }
    public Comentario getComentario() {
        return this.comentario;
    }
    
    public void setComentario(Comentario comentario) {
        this.comentario = comentario;
    }
    public String getComentario_1() {
        return this.comentario_1;
    }
    
    public void setComentario_1(String comentario_1) {
        this.comentario_1 = comentario_1;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


