package model.pojos;
// Generated 15/11/2012 09:54:45 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * StatusUsuario generated by hbm2java
 */
public class StatusUsuario  implements java.io.Serializable {


     private int idStatusUsuario;
     private String descripcion;
     private Set usuarios = new HashSet(0);

    public StatusUsuario() {
    }

	
    public StatusUsuario(int idStatusUsuario, String descripcion) {
        this.idStatusUsuario = idStatusUsuario;
        this.descripcion = descripcion;
    }
    public StatusUsuario(int idStatusUsuario, String descripcion, Set usuarios) {
       this.idStatusUsuario = idStatusUsuario;
       this.descripcion = descripcion;
       this.usuarios = usuarios;
    }
   
    public int getIdStatusUsuario() {
        return this.idStatusUsuario;
    }
    
    public void setIdStatusUsuario(int idStatusUsuario) {
        this.idStatusUsuario = idStatusUsuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


