package model.pojos;
// Generated 15/11/2012 05:32:04 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private int idUsuario;
    private Rol rol;
    private StatusUsuario statusUsuario;
    private String primerNombre;
    private String segundoNombre;
    private String apellidoPaterno;
    private String apellidoMaterno;
    private String nick;
    private Character sexo;
    private String usuario;
    private String password;
    private Date fechaNacimiento;
    private String email;
    private String rutaFoto;
    private Set comentariosForUsuarioEmisor = new HashSet(0);
    private Set comentariosForUsuarioReceptor = new HashSet(0);
    private Set amistadsForIdUsuario1 = new HashSet(0);
    private Set amistadsForIdUsuario2 = new HashSet(0);

    public Usuario() {
    }

    public Usuario(int idUsuario, Rol rol, StatusUsuario statusUsuario, String usuario, String password, String email,String rutaFoto) {
        this.idUsuario = idUsuario;
        this.rol = rol;
        this.statusUsuario = statusUsuario;
        this.usuario = usuario;
        this.password = password;
        this.email = email;
        this.rutaFoto=rutaFoto;
    }

    public Usuario(int idUsuario, Rol rol, StatusUsuario statusUsuario, String primerNombre, String segundoNombre, String apellidoPaterno, String apellidoMaterno, String nick, Character sexo, String usuario, String password, Date fechaNacimiento, String email, Set comentariosForUsuarioEmisor, Set comentariosForUsuarioReceptor, Set amistadsForIdUsuario1, Set amistadsForIdUsuario2) {
        this.idUsuario = idUsuario;
        this.rol = rol;
        this.statusUsuario = statusUsuario;
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.nick = nick;
        this.sexo = sexo;
        this.usuario = usuario;
        this.password = password;
        this.fechaNacimiento = fechaNacimiento;
        this.email = email;
        this.comentariosForUsuarioEmisor = comentariosForUsuarioEmisor;
        this.comentariosForUsuarioReceptor = comentariosForUsuarioReceptor;
        this.amistadsForIdUsuario1 = amistadsForIdUsuario1;
        this.amistadsForIdUsuario2 = amistadsForIdUsuario2;
    }

    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    public StatusUsuario getStatusUsuario() {
        return this.statusUsuario;
    }

    public void setStatusUsuario(StatusUsuario statusUsuario) {
        this.statusUsuario = statusUsuario;
    }

    public String getPrimerNombre() {
        return this.primerNombre;
    }

    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    public String getSegundoNombre() {
        return this.segundoNombre;
    }

    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }

    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }

    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    public String getNick() {
        return this.nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public Character getSexo() {
        return this.sexo;
    }

    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set getComentariosForUsuarioEmisor() {
        return this.comentariosForUsuarioEmisor;
    }

    public void setComentariosForUsuarioEmisor(Set comentariosForUsuarioEmisor) {
        this.comentariosForUsuarioEmisor = comentariosForUsuarioEmisor;
    }

    public Set getComentariosForUsuarioReceptor() {
        return this.comentariosForUsuarioReceptor;
    }

    public void setComentariosForUsuarioReceptor(Set comentariosForUsuarioReceptor) {
        this.comentariosForUsuarioReceptor = comentariosForUsuarioReceptor;
    }

    public Set getAmistadsForIdUsuario1() {
        return this.amistadsForIdUsuario1;
    }

    public void setAmistadsForIdUsuario1(Set amistadsForIdUsuario1) {
        this.amistadsForIdUsuario1 = amistadsForIdUsuario1;
    }

    public Set getAmistadsForIdUsuario2() {
        return this.amistadsForIdUsuario2;
    }

    public void setAmistadsForIdUsuario2(Set amistadsForIdUsuario2) {
        this.amistadsForIdUsuario2 = amistadsForIdUsuario2;
    }

    /**
     * Regresa a los usuarios que son amigos de la instancia y que tienen esatus
     * activo
     *
     * @return
     */
    public Set<Usuario> getAllAmistades() {
        Set<Amistad> amistadsForIdUsuario11 = getAmistadsForIdUsuario1();
        Set<Amistad> amistadsForIdUsuario21 = getAmistadsForIdUsuario2();
        Set<Usuario> resultado = new HashSet<Usuario>();
        for (Amistad am1 : amistadsForIdUsuario11) {
            if (am1.getStatusAmistad().getIdStatusAmistad() == 1) {

                resultado.add(am1.getUsuarioByIdUsuario2());
            }
        }
        for (Amistad am2 : amistadsForIdUsuario21) {
            if (am2.getStatusAmistad().getIdStatusAmistad() == 1) {

                resultado.add(am2.getUsuarioByIdUsuario1());
            }
        }
        return resultado;
    }

    /**
     * @return the rutaFoto
     */
    public String getRutaFoto() {
        return rutaFoto;
    }

    /**
     * @param rutaFoto the rutaFoto to set
     */
    public void setRutaFoto(String rutaFoto) {
        this.rutaFoto = rutaFoto;
    }
}
